version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.25
    - 14.14.26
    - 14.14.27
    - 14.14.28
    - 14.14.30
    - 14.14.39
    - 14.14.41
    - 15.0.0
  - dependency-name: "@types/jest"
    versions:
    - 26.0.20
    - 26.0.21
    - 26.0.22
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.0
    - 7.13.10
    - 7.13.12
    - 7.13.15
    - 7.13.8
    - 7.13.9
  - dependency-name: "@babel/core"
    versions:
    - 7.13.1
    - 7.13.10
    - 7.13.13
    - 7.13.14
    - 7.13.15
    - 7.13.8
  - dependency-name: "@babel/cli"
    versions:
    - 7.13.0
    - 7.13.10
    - 7.13.14
  - dependency-name: "@babel/plugin-proposal-optional-chaining"
    versions:
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.0
    - 7.13.12
    - 7.13.8
  - dependency-name: "@babel/runtime-corejs2"
    versions:
    - 7.13.10
    - 7.13.7
    - 7.13.8
    - 7.13.9
  - dependency-name: typescript
    versions:
    - 4.2.2
    - 4.2.3
  - dependency-name: lodash
    versions:
    - 4.17.21
  - dependency-name: webpack
    versions:
    - 4.46.0
  - dependency-name: "@babel/plugin-transform-arrow-functions"
    versions:
    - 7.12.13
    - 7.13.0
  - dependency-name: "@babel/plugin-transform-modules-commonjs"
    versions:
    - 7.12.13
    - 7.13.0
  - dependency-name: taiko
    versions:
    - 1.2.0
    - 1.2.1
  - dependency-name: eslint-plugin-vue
    versions:
    - 7.5.0
  - dependency-name: object-path
    versions:
    - 0.11.5
  - dependency-name: terser-webpack-plugin
    versions:
    - 4.2.3
  - dependency-name: antlr4
    versions:
    - 4.9.1
  - dependency-name: webpack-cli
    versions:
    - 4.4.0
    - 4.5.0
  - dependency-name: ini
    versions:
    - 1.3.8
  - dependency-name: marked
    versions:
    - 1.2.8
